### PR TITLE
add prettier alongisde .editorconfig

### LINKED ISSUE #5: Github Checks

### PR DESCRIPTION
**Pull request by mrshmllow**
Prettier automatically inherits any .editorconfig

closes #5

### CODE REVIEW

**Comment by isabelroses** [comment]
The PR looks good but it might be worth using @getchoo's https://github.com/getchoo/flake-checks

**Comment by mrshmllow** [comment]
Personally I would really love to move to flake-parts for commit hooks and such

**Comment by mrshmllow** [comment]
Also maybe we switch to biome 🤔 (But it doesnt have clean editorconfig support yet https://github.com/biomejs/biome/issues/1724)

**Comment by isabelroses** [comment]
> Also maybe we switch to biome 🤔 (But it doesnt have clean editorconfig support yet [biomejs/biome#1724](https://github.com/biomejs/biome/issues/1724))

good catch, I didn't realise there was no prettier check.

**Review by isabelroses — APPROVED** [review]

**Pull request merged**
